# Generated by Django 5.0 on 2025-09-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_review_options_review_parent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="movies_revi_movie_i_818d47_idx",
        ),
    ]
